name: Health check

on:
  schedule:
    - cron: '* * * * 6'

jobs:
  schedule_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check pokedex URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://proud-fog-1145.fly.dev/health
          follow-redirect: false
          max-attempts: 2
          retry-delay: 5s
          retry-all: true
