name: Testing stuff

on:
  push:
    branches:
      - master

  pull_request:
    branches: [master]
    types: [opened, synchronize]
env:
  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}

jobs:
  testing:
    env:
      SKIP_DEPLOY_AND_TAG: ${{ contains( join( env.COMMIT_MESSAGES ), '#skip' ) }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: print env commit-msg
        run: echo "$COMMIT_MESSAGES"
      - name: print env skip-deploy
        run: echo "$SKIP_DEPLOY_AND_TAG"
      - name: test expressions
        if: ${{ env.SKIP_DEPLOY_AND_TAG == 'true' }}
        run: echo "SKIP_DEPLOY_AND_TAG=TRUE"
        if: ${{ !env.SKIP_DEPLOY_AND_TAG == 'true' }}
        run: echo "SKIP_DEPLOY_AND_TAG=FALSE"
